### ISSUE TITLE
Revamp node flags settings using charts values

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#142]
When using the node helm chart, it is really hard to figure out whether flags should be set in the chart values or inside `node.flags`. The situation can be improved:
- [x]  List common substrate flags option and allow configuring them with chart values (--unsafe-rpc-external, --telemetry-url, --log). We shouldn't include more esoteric flags (polkadot/cumulus specific)
- [x] The `pruning` and `database` options should be under `chainData` and `relayChainData`.
- [x] Preferentially use default values (ie. not setting the flags when value=null)
- [x] relayChainFlags should have `--name=${POD_NAME}"` by default and the same telemetry URLs as the main chain.
- [x] Add script on node startup to check if any passed flags is in the list of flags that are handled by chart values and fail if it's the case
- [x] Also forbid to set flags which don't make sense for the chart: `--ws-port` and `--rpc-port`

**Comment by PierreBesson** [comment]
Should we completely revamp the collator options ? It would be a pretty drastic change but it will make things more readable.

We could change this:
```
  collator:
    isParachain: true
    relayChain: rococo
    relayChainDatabase: paritydb
    relayChainPruning: 1000
    relayChainCustomChainspecUrl: "https://paritytech.github.io/chainspecs/versi/relaychain/chainspec.json"
    relayChainData:
      chainPath: rococo_v2_2
      GCSBucketUrl: gs://rococo-blockstore-backups/rococo-paritydb-prune
      storageClass: ssd-csi
      volumeSize: 30G
    relayChainKeystore:
      mountInMemory: true
```
Into:
```
isParachain: true
collatorRelayChain:
  chain: rococo
  database: paritydb
  pruning: 1000
  customChainspecUrl:
  chainData:
      chainPath: rococo_v2_2
      GCSBucketUrl: gs://**
      storageClass: ssd-csi
      volumeSize: 50G
  chainKeystore:
      mountInMemory: true
```

This has the the big advantage of keeping same options names to configure the collator relay chain just indented under `collatorRelayChain`
