### ISSUE TITLE
[node] Fix readinessProbe

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/helm-charts#167]
Staring from polkadot v0.9.28, logs are full with following lines: 
```
2022-10-03 20:29:32 Accepting new connection 1/100
2022-10-03 20:29:33 Rejected connection: Transport(i/o error: unexpected end of file
Caused by:
     unexpected end of file)
```

It is caused by [readinessProbe](https://github.com/paritytech/helm-charts/blob/main/charts/node/templates/statefulset.yaml#L566) it uses `tcpSocket` to check if the port is open.
Previously port was closed until the node is synced but the substrate network was refactored several times and now this is not the case.

**Comment by BulatSaif** [comment]
we can use `health` endpoint as here:  https://github.com/w3f/polkadot-charts/blob/master/charts/polkadot/templates/statefulset.yaml#L149

**Comment by PierreBesson** [comment]
This is because we use a TCP probe to check if node is ready, eventually it should be replaced by a call to the readiness endpoint after it as been added to Subtrate: https://github.com/paritytech/substrate/issues/1017
I agree with @BulatSaif, it should be replaced by a call to the http /health endpoint in the meantime.

**Comment by PierreBesson** [comment]
Considering we already have a startup probe:
```
          # On startup, retry the connection to the /health endpoint every 10s for 5 min before killing the container
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            httpGet:
              path: /health
              port: http-rpc
```
We might be better off removing this readiness probe entirely as it doesn't even work anymore since the adoption of jsonrpsee by substrate.

**Comment by niklasad1** [comment]
@BulatSaif 

These logs are from the `websocket server` after looking the `readiness probe` it has `http-rpc` which I thought was only run against the HTTP port. Is it expected to be sent to the websocket server as well? IMHO, it's makes sense to do it against both the http and ws server to detect when they "ok".

FYI, we have refactored to `jsonrpsee ws server and http server` to a mixed server which supports `http and ws` on the same port. Thus, after that `/health` should check if the websocket server "is healthy" as well.

Not released yet but should come soonish in substrate.

**Comment by PierreBesson** [comment]
@niklasad1 this is the readiness probe:

```
readinessProbe:
            failureThreshold: 8640
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            # Important: the readiness probe will only work properly if the WS endpoint is exposed with --ws-external
            tcpSocket:
              port: websocket-rpc
```

, from what I can tell, it is actually working as intended from the kubernetes point of view but it is just producing this annoying log in substrate as is not a valid request for jsonrpsee, just a tcp connection check like you would do manually with telnet.

Happy to learn about this future merge of the http and ws port. May I ask how will backward compatibility with the current dual port system be handled ?
