### ISSUE TITLE
Implement Statefulset updateStrategy.rollingUpdate.maxUnavailable for the node chart

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#191]
Available in k8s 1.24+, the [maximum unavailable pods](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#maximum-unavailable-pods) rolling update strategy will make it much smoother to roll out updates to Statefulset which can currently be done 1 pod at a time.

We should be careful to use the proper helm kubernetes version checks in the templates to ensure compatibility with the user cluster.

**Comment by PierreBesson** [comment]
@Sudo-Whodo this looks good. I would personally set this in the chart values.yaml to follow our conventions.
```
node:
  updateStrategy:
     enabled: false # Remark; we don't want add any config if disabled to leave Kubernetes defaults
     type: RollingUpdate # or OnDelete
     maxUnavailable: 1
```
