### ISSUE TITLE
Run all containers as read-only and prevent privilege escalation by default

### ISSUE THREAD

**Issue by chevdor** [paritytech/helm-charts#22]
If I recall, the polkadot images are pretty friendly with running as `read-only` as long as you use a volume for the chain data.

```
   containers:
      - name: mynode
         image: <the_image>
         securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
```

For tmp containers where we do not want to mount a volume, the solution to keep running the containe as `read-only` is to mount whatever folder where the node needs to write as tmpfs.

**Comment by PierreBesson** [comment]
Hello, I have tried those options in our cluster (version:v1.20.9-gke.1001) but they don't seem to be supported. So I don't think we should be setting those as defaults.

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "readOnlyRootFilesystem" in io.k8s.api.core.v1.PodSecurityContext]
```
However nothing prevents you from running them by setting the following values for the chart:
```
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 100
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
```
> For tmp containers where we do not want to mount a volume, the solution to keep running the containe as read-only is to mount whatever folder where the node needs to write as tmpfs.

The chart already assume usage of a Persistent Volume in all cases.

I think the way to go would be to define a [PodSecurityPolicy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) although this API [will be replaced by something else in the future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/).
