### ISSUE TITLE
[node] incorrect value for public-addr if service type is LoadBalancer

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/helm-charts#277]
Helm chart sets incorrect value for `public-addr` if service type is` LoadBalancer`

Here example of config for collator:
```
    perNodeServices:
      relayP2pService:
        enabled: true
        type: NodePort
      paraP2pService:
        enabled: true
        type: LoadBalancer
        port: 30333
        externalDns:
          enabled: true
          hostname: example.io.
          ttl: 60
        ws:
          enabled: true
          port: 30335
      setPublicAddressToExternalIp:
        enabled: true
```
and following variable will be set by pod:
```
{{- /* For non NodePort services, set the p2p port to value configured in `paraP2pService.port` */}}
PARA_CHAIN_P2P_PORT={{ $.Values.node.perNodeServices.paraP2pService.port | quote }}
EXTERNAL_IP=$(curl {{ .Values.node.perNodeServices.setPublicAddressToExternalIp.ipRetrievalServiceUrl }})
```
`public-addr` flag has following value:
```
--public-addr=/ip4/${EXTERNAL_IP}/tcp/${PARA_CHAIN_P2P_PORT}
```
This will be resulting to:
```
--public-addr=/ip4/node_ip:30333
```
this is incorrect, it should be either:
```
--public-addr=/ip4/node_ip:NodePort
```
or 
```
--public-addr=/ip4/LoadBalancer_IP:30333
```
