### ISSUE TITLE
Allow fixing the p2p port

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#29]
Automatic node port discovery was introduced in #28, however in some cases the operator will not want / be able to open a large range of ports (30000-32767) on their Kubernetes nodes.

An option should be added to fix the attributed nodePort, however in this case it might be impossible to support more than 1 replica for the statefulset as fixing the port will result in a port conflict for the second replica.

**Comment by dblane-digicatapult** [comment]
When using type LoadBalancer our implementation would vary depending on the cloudProvider being used when we query a service to get the external address which is either an FQDN or an IP,  which we then need to advertise when using `--public-addr`

AWS example:
```
status:
  loadBalancer:
    ingress:
    - hostname: some-loadbalancer-hostname.eu-west-1.elb.amazonaws.com
```

Where as GCP will return:
```
status:
    loadBalancer:
      ingress:
      - ip: 111.111.111.111
```

This complicates how we then advertise, do we want to detect the address's format and then setup our multiaddr format based on if its an IP or FQDN?  The current kubectl image we are using for the init container that queries these services has no `dig` or `hosts` command so reducing an FQDN to either a single or an array of IPs is challenging.

Also currently our naming is very specific to NodePort `node.perNodeServices.createP2pNodePortService` Do we want to change something more generically named for the p2p service? E.G.
```
  perNodeServices:
    createApiService: true
    createP2pService: true
    p2pServiceType: LoadBalancer  # Must be type ClusterIP, NodePort or LoadBalancer
    setPublicAddressToExternal:
      enabled: true
      ipRetrievalServiceUrl: https://ifconfig.io/ip
```
