### ISSUE TITLE
Add support for Gateway API as alternative to ingress

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#308]
https://kubernetes.io/blog/2023/10/31/gateway-api-ga/

**Comment by PierreBesson** [comment]
By introducing the Gateway API to expose node RPC endpoints, we should strive to make it easier to use for non devops users than the current ingress config.

Right now to expose a node RPC, we need a config which looks like this:

```
  ingress:
    enabled: true
    rules:
      - host: versi-tick-500-rpc.parity-versi.parity.io # This should be the only property passed to the gateway
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: versi-tick-500-node # The service name could be automatically derived from the release name
                  port:
                    number: 9944 # Port could be automatically set
    tls:
      - secretName: versi-tick-500-rpc.parity-versi.parity.io
        hosts:
          - versi-tick-500-rpc.parity-versi.parity.io
```
