### ISSUE TITLE
Allow annotating created p2p services

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/helm-charts#33]
It would be useful to be able to independently annotate the auto-created p2p Services.
This would enable using [kubernetes-sigs/external-dns](https://github.com/kubernetes-sigs/external-dns) to manage Bootnodes / RPC nodes DNS entries.

For example:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    external-dns.alpha.kubernetes.io/hostname: bootnode.testnet.parity.io.
 ```
