### ISSUE TITLE
statefulSet inject keys doesn't work

### ISSUE THREAD

**Issue by dblane-digicatapult** [paritytech/helm-charts#36]
When iterating over the `{{- range $index, $key := .Values.node.keys }}` the helm chart fails to correctly insert `values.node.command` in the subsequent initContainer command this is because when you use a range you change the scope of the Values.

Consider the following values.yaml
```
node:
    keys: 
    - type: "gran"
      scheme: "ed25519"
      seed: "//Blah"
 ```
 This results in the following error: `nil pointer evaluating interface {}.node` as node.command is no longer in scope.
 
 The following works but is obviously undesirable:
```
node:
   keys:
   - type: "gran"
      scheme: "ed25519"
      seed: "//Blah"
      Values:
        node:
          command: "command"
```
An easy fix is evaluating `{{ .Values.node.command }}` as `$COMMAND` and setting that as an envar similar to how we set `{{ .Values.node.chain }}` in the same init container.  Alternatively we can set `{{ .Values.node.command }}` as a helm variable before the loop.

Happy to put up a fix for this if you let me know your preferred method.
