### ISSUE TITLE
Telemetry chart does not install "by default"

### ISSUE THREAD

**Issue by chevdor** [paritytech/helm-charts#7]
Here is my test:
```
NS=testing
kubectl create ns $NS
helm install substrate-telemetry parity/substrate-telemetry -n $NS
```

The 3 deployments fail:

![image](https://user-images.githubusercontent.com/738724/130421946-5df2fef2-db9c-49fc-917a-c2f367be475d.png)

![image](https://user-images.githubusercontent.com/738724/130421981-d25b0160-449c-4992-b6f1-9c2f986bf19c.png)

![image](https://user-images.githubusercontent.com/738724/130422022-c13f0cab-9aad-45fc-9cb2-6cc3c3618503.png)

NOTE: In the meantime, I did install a LoadBalancer in my cluster but the lack of it does not seem to be the issue.

**Comment by chevdor** [comment]
@arshamparity I see you are on it so I will no go for a fix but I tested a few things:

## services
the services look ok, the issues are the pods

## core: binary name

the core pod is set for using `telemetry_core` but it has only a `telemetry` executable. So either the image is old, or the chart does not match the new image. I think this is the 'latest' image is simply too old for this chart.

## frontend: readyness probe

One option to fix that is to change in `frontend-deployment.yaml`:
```
  livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```
into:
```
  livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend.port }}
```

## shard: binary name

same issue than 'core':
```
docker run --rm -it --entrypoint=bash docker.io/parity/substrate-telemetry-backend:latest -c 'ls -al'
total 7264
drwxr-xr-x 1 root root    4096 May 21 12:04 .
drwxr-xr-x 1 root root    4096 May 11 00:00 ..
-rwxr-xr-x 1 root root 7428448 May 21 12:04 telemetry
```
